### PR TITLE
Update google provider 4.x

### PR DESCRIPTION
**Pull request by thiesen**

### CODE REVIEW

**Review by mariux — CHANGES_REQUESTED** [review]
needs to use the 4.x enabled IAM module

**Comment by thiesen** [comment]
@mariux updated to v0.0.2 that should be available when https://github.com/mineiros-io/terraform-google-folder-iam/pull/11 gets merged!

**Review by mariux — APPROVED** [review]
lgtm

**Comment by mariux** [comment]
released dependent module

**Pull request merged**
